### PR TITLE
Added Support for Remote-DevTools

### PR DESCRIPTION
**Pull request by BuchholzTim**

### CODE REVIEW

**Comment by BuchholzTim** [comment]
To test if it works properly:

- Startup App with `REACT_APP_PRODUCTION=true` -> Redux should be inactive in Extension and remotedev.io/local
- Startup with  `REACT_APP_PRODUCTION=false` & `REACT_APP_SAFARI=false` -> Redux should be active as Extension and not on remotedev.io/local
- Startup with  `REACT_APP_PRODUCTION=false` & `REACT_APP_SAFARI=true` -> Redux should be inactive as Extension and active on remotedev.io/local

**Comment by MarcBollmann** [comment]
This Error appears when trying to connect remotedev.io

image

**Review by MarcBollmann — CHANGES_REQUESTED** [review]
Error appears
Same problem found over here: https://github.com/zalmoxisus/remote-redux-devtools/issues/68

**Comment by BuchholzTim** [comment]
Cannot Reproduce your error.
A suggested fix looks like this:

- Install Remote-Dev-Server locally as dependency in your application and start the server
- go to remotedev.io/local and set the server-settings to your locally running remote-dev-server

I quickly tried integrating it but ran into some other errors. But i can't really point out, why it works for me and not for you. Seems like some people do have this problem and others haven't. Some people report the problem disappearing after trying several times..

The issue could also be linked to the fact, that their SSL-Cert is expired since December 2019.

**Comment by MarcBollmann** [comment]
I recommend that @Preefix tries it out, because he's the person who needs it.

**Comment by BuchholzTim** [comment]
@GeiserRafael had the same issue.

I guess I don't have it because I run it inside the WSL.

**Comment by MarcBollmann** [comment]
I fixed it for me. 
Problem was indeed the invalid-certificate from http://remotedev.io/ . 

To ignore the certifcate error:
1. Access the site: http://remotedev.io/ then your browser should give you a warning because of the invalid certificate **click "proceed to unsafe site"**
2. After that the browser safes this as a choice (which @BuchholzTim maybe did on his local browser if I remember correctly -> thats why it works for him maybe)
3. Then click on Local Development to proceed to http://remotedev.io/local/
4. Now it works for me because the browser remembers and ignores the invalid certficate!

**Review by MarcBollmann — APPROVED** [review]
Error fixed @GeiserRafael can try it

**Pull request merged**
